type: object
properties:
  realm:
    $ref: './index.openapi.yaml#/components/schemas/Realm'
    description: |-
      レルムの定義。レルムは、SPNの基本的な単位であり、DNSゾーン、仮想ホスト、ルーティングチェーン、SPN Hub、サービスなどを含む。
  zones:
    type: array
    items:
      $ref: './index.openapi.yaml#/components/schemas/Zone'
    description: |-
      レルムに属するゾーンのリスト。各ゾーンは、DNSレコードを管理するための情報を含む。
  subdomains:
    type: array
    items:
      $ref: './index.openapi.yaml#/components/schemas/Subdomain'
    description: |-
      レルムに属するサブドメインのリスト。
  virtualHosts:
    type: array
    items:
      $ref: './index.openapi.yaml#/components/schemas/VirtualHost'
    description: |-
      レルムに属する仮想ホストのリスト。各仮想ホストは、FQDN、ルーティングチェーン、SSL/TLS証明書などの情報を含む。
  routingChains:
    type: array
    items:
      $ref: './index.openapi.yaml#/components/schemas/RoutingChain'
    description: |-
      レルムに属するルーティングチェーンのリスト。各ルーティングチェーンは、リクエストの処理を行うためのルールの集合を含む。
  hubs:
    type: array
    items:
      $ref: './index.openapi.yaml#/components/schemas/Hub'
    description: |-
      レルムに属する SPN Hub のリスト。各 SPN Hub は、SPN Hub の名前、FQDN、サーバ証明書、サーバ証明書の秘密鍵などの情報を含む。
  services:
    type: array
    items:
      $ref: './index.openapi.yaml#/components/schemas/Service'
    description: |-
      レルムに属するサービスのリスト。各サービスは、サービスの名前、URN、タイトル、説明、提供者、利用者などの情報を含む。 
additionalProperties: false

